[package]
name = "signer-node"
version = "0.1.0"
authors = ["Kohei Taniguchi <kohei@chaintope.com>"]
edition = "2018"

[dependencies]
http = "0.1.17"
bitcoin = "0.17.0"
secp256k1 = "0.12.2"
jsonrpc-core = "11.0.0"
jsonrpc-core-client = "11.0.0"
jsonrpc-derive = "11.0.0"