[package]
name = "signer-node"
version = "0.1.0"
authors = ["Kohei Taniguchi <kohei@chaintope.com>"]
edition = "2018"

[dependencies]
http = "0.1.17"
bitcoin = "0.17.0"
secp256k1 = "0.12.2"
log = "0.4.6"
serde = "1.0.91"
serde_json = "1.0.39"
bitcoin_hashes = "0.3.2"
jsonrpc = "0.11.0"