name: tapyrus-signer 
version: &version v0.3.1
summary: Tapyrus Signer
description: |
        Tapyrus Signer Node 
license: MIT
base: core18
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  tapyrus-signer:
    source: https://github.com/chaintope/tapyrus-signer.git
    source-tag: *version
    plugin: rust
    build-packages:
      - libgmp3-dev
