name: tapyrus-signer 
version: git
summary: Tapyrus Signer
description: |
        Tapyrus Signer Node 
license: MIT
base: core18
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  daemon:
    command: tapyrus-signerd
    plugs: [network]

parts:
  tapyrus-signer:
    source: https://github.com/chaintope/tapyrus-signer.git
    plugin: rust
    build-packages:
      - libgmp3-dev
