name: tapyrus-signer 
version: git
summary: Tapyrus Signer
description: |
        Tapyrus Signer Node 
license: MIT
base: core18
grade: stable
confinement: strict

architectures:
  - build-on: [s390x, ppc64el, arm64, amd64, i386]

apps:
  service:
    command: tapyrus-signerd
    plugs: [network]
    daemon: simple
  daemon:
    command: tapyrus-signerd
    plugs: [network]
  setup:
    command: tapyrus-setup

parts:
  tapyrus-signer:
    source: https://github.com/chaintope/tapyrus-signer.git
    plugin: rust
    build-packages:
      - libgmp3-dev
    stage-packages:
      - libgmp10
